import { HttpException, HttpStatus } from '@nestjs/common'

export type DomainErrorCode =
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'PRODUCT_NOT_FOUND'
  | 'AMOUNT_OUT_OF_RANGE'
  | 'TERM_OUT_OF_RANGE'
  | 'CREDIT_NOT_ELIGIBLE'
  | 'FIRST_CREDIT_CAP_EXCEEDED'
  | 'DTI_EXCEEDED'
  | 'INVALID_TRANSITION'
  | 'SEGREGATION_OF_DUTIES_VIOLATION'
  | 'BANK_ACCOUNT_NOT_VERIFIED'
  | 'CONTRACT_NOT_ACCEPTED'
  | 'CONTRACT_ALREADY_ACCEPTED'
  | 'INTERNAL_ERROR'

const STATUS_BY_CODE: Record<DomainErrorCode, HttpStatus> = {
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  PRODUCT_NOT_FOUND: HttpStatus.NOT_FOUND,
  AMOUNT_OUT_OF_RANGE: HttpStatus.BAD_REQUEST,
  TERM_OUT_OF_RANGE: HttpStatus.BAD_REQUEST,
  CREDIT_NOT_ELIGIBLE: HttpStatus.UNPROCESSABLE_ENTITY,
  FIRST_CREDIT_CAP_EXCEEDED: HttpStatus.UNPROCESSABLE_ENTITY,
  DTI_EXCEEDED: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_TRANSITION: HttpStatus.CONFLICT,
  SEGREGATION_OF_DUTIES_VIOLATION: HttpStatus.FORBIDDEN,
  BANK_ACCOUNT_NOT_VERIFIED: HttpStatus.UNPROCESSABLE_ENTITY,
  CONTRACT_NOT_ACCEPTED: HttpStatus.UNPROCESSABLE_ENTITY,
  CONTRACT_ALREADY_ACCEPTED: HttpStatus.CONFLICT,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
}

export class DomainError extends HttpException {
  constructor(
    public readonly code: DomainErrorCode,
    message: string,
  ) {
    super({ code, message }, STATUS_BY_CODE[code])
  }
}
